#!/usr/bin/env bash
set -e

if ! hash brew 2>/dev/null; then
  echo "✖ Homebrew not found. Please install: https://brew.sh/"
  exit 1
else
  echo "✓ Found homebrew"
fi

if ! hash python3 2>/dev/null; then
  read -p "✖ 'python3' not found. Would you like to install it? [Y/n] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy\n]$ ]]
  then
    brew install python3 && true
  else
    exit 1
  fi
else
  echo "✓ Found python3"
fi
