#!/usr/bin/env bash

set -e

# Usage
#
# ./release
#

# Publish
# First cleanup dist folder
rm -f dist/*
# Build the dist
python3 setup.py sdist bdist_wheel
# check
twine check dist/*
# publish to pypi
twine upload dist/*

