#!/usr/bin/env bash
set -e
# TODO this file could be gone
RELEASED_LOG="/tmp/python-pending-changes.md"
THIS_VERSION=$(./scripts/bump --this-version)

# Finally need to update the full changelog
./scripts/changelog
git add CHANGELOG.md
git commit -m "Update Changelog for Release $THIS_VERSION"
git push origin master

# Publish
# First cleanup dist folder
rm -f dist/*
# Build the dist
python3 setup.py sdist bdist_wheel
# check
twine check dist/*
# publish to pypi
twine upload dist/*

# create release
hub release create -c -F $RELEASED_LOG $THIS_VERSION

# Copy-pasteable messages for announcments
echo ":python: Python $THIS_VERSION Released :python:"
echo ":pypi: PyPi: https://pypi.org/project/recurly/$THIS_VERSION/"
echo "Release: https://github.com/recurly/recurly-client-python/releases/tag/$THIS_VERSION"
echo "Changelog:"
echo "\`\`\`"
cat "$RELEASED_LOG"
echo "\`\`\`"
