name: CI
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }} tests
    strategy:
      matrix:
        python: [2.7, 3.7, 3.8, 3.9]
        os: [ubuntu-latest]
        include:
          # Python 3.6 is not included in ubuntu latest (currently 22)
          - python: 3.6
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: ./scripts/build
      - run: ./scripts/test
  buildall:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: build
    steps:
      - name: Check build matrix status
        if: ${{ needs.build.result != 'success' }}
        run: exit 1
