name: Security check - Semgrep

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - staging
      - main
      - master
      - qa

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: r7kamura/semgrepper@v0
        continue-on-error: true